require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
#install! 'cocoapods', :deterministic_uuids => false

platform :ios, '13.0'

target 'example' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'exampleTests' do
    inherit! :complete
    # Pods for testing
  end

#   pod "NMSSH-riden", :git => "../../../NMSSH", :tag => "2.6.3"
  pod "react-native-riden-ssh", :path => "../node_modules/@ridenui/react-native-riden-ssh-test/"
  # pod "SwifterSwiftSSH", :path => "../../../swifter-swift-ssh"
  pod "SwifterSwiftSSH", :git => "../../../swifter-swift-ssh", :tag => "1.1.4"

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings.delete('IPHONEOS_DEPLOYMENT_TARGET')
        config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
      end
      case target.name
      when 'RCT-Folly'
        target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
        end
      end
    end
  end
end
